crown-court-contribution/Dockerfile, crown-court-contribution/docker-compose.yml, crown-court-contribution/src/main/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=> Changed Port

README.md, crown-court-contribution/Dockerfile
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-503)
- Added UID for appuser in Dockerfile
- Updated Readme
=> Lcam 503 add numeric docker user

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionRulesService.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/ContributionRulesServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-392)
Migrate the business rule from contribution_rule_applies stored procedure.
=> LCAM-392|Migrate the business rule from contribution_rule_applies SP

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/config/ServicesConfiguration.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/dto/FinancialAssessmentDTO.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/dto/PassportAssessmentDTO.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/dto/RepOrderDTO.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataService.java, crown-court-contribution/src/main/resources/application.yaml, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/config/MockServicesConfiguration.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/data/builder/TestModelDataBuilder.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/ContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-379)
- added service method for `checkReassessment`
- added DTOs and maatAPIClient calls for `getContributionCount` and `getRepOrderByRepId`
- added unit tests
=> Lcam 379 check reassessment rule

crown-court-contribution/build.gradle, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataService.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-686)
upgrade common rest api
=> LCAM-686-upgrade common rest api

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/dto/RepOrderDTO.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionService.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/data/builder/TestModelDataBuilder.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/ContributionServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=> Application Status Changed Function

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/AppealContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataService.java, crown-court-contribution/src/main/resources/application.yaml, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionIntegrationTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/AppealContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-408)
Changes made to retrieve list of contribution 
=> LCAM-408-find contribution

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionService.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/ContributionServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-408)
Migrate hasContributionBeenSent procedure 
=> LCAM-408-migrate-hasContributionBeenSent

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/dto/ContributionDTO.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/CompareContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/test.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/staticdata/enums/CorrespondenceStatus.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/data/builder/TestModelDataBuilder.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/CompareContributionServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-400)
- business logic for contribution.compare_contribution into C3 service
- Added Unit test
=> Lcam 400 compare contribution

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-637)
Updated circleci config and env variables to use short lived credentials
=> Lcam 637 short lived creds ecr

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/CalculateContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionService.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/CalculateContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/ContributionServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-399)
Resolved circular dependancy  
=> LCAM-399-calculate-contribution-changes

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/builder/MaatCalculateContributionResponseMapper.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/CalculateContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionService.java, crown-court-contribution/src/main/resources/schemas/maat-api/MaatCalculateContributionResponse.json, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/data/builder/TestModelDataBuilder.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-930)
=> LCAM-930|Update response with processActivity flag

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionController.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionService.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionControllerTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionIntegrationTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-929
=> Get Contributions Summary

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionController.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionControllerTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionIntegrationTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-838)
=> Added endpoint URL

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/builder/ContributionDTOBuilder.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/builder/CreateContributionRequestMapper.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/builder/GetContributionAmountRequestMapper.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/builder/MaatCalculateContributionResponseBuilder.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/builder/MaatCalculateContributionResponseMapper.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtCalculateContributionController.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionController.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/AppealContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/validation/CalculateContributionValidator.java, crown-court-contribution/src/main/resources/schemas/maat-api/ApiMaatCalculateContributionRequest.json, crown-court-contribution/src/main/resources/schemas/maat-api/ApiMaatCalculateContributionResponse.json, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/builder/MaatCalculateContributionResponseMapperTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionControllerTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/CrownCourtContributionIntegrationTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/data/builder/TestModelDataBuilder.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/AppealContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/validation/AppealContributionValidatorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-838)
Refactor the schemas in preparation of MAAT integration.
=> LCAM-838|Refactor the schemas in preparation of MAAT integration

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/staticdata/enums/AssessmentResult.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-838)
Add missing enum values for Assessment Result.
=> Add missing enum values for Assessment Result

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/controller/ContributionController.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/AppealContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/staticdata/enums/HardshipReviewDetailType.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/ContributionControllerContributionIntegrationTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/ContributionControllerTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/enums/staticdata/HardshipReviewDetailTypeTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-977)
Added HardshipReviewDetailType enum and passing the enum value on the request to calculate hardship for detail.
=> LCAM-977|Update calculate hardship for detail request

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/controller/ContributionController.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/dto/CalculateContributionDTO.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/AppealContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/CompareContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/CrimeHardshipService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataService.java, crown-court-contribution/src/main/resources/schemas/maat-api/apiCalculateHardshipByDetailRequest.json, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/ContributionControllerTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/data/builder/TestModelDataBuilder.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/AppealContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/CompareContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/ContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1003)
Removed the usage of laaTransactionId.
Updated PR template and codeowners.
=> LCAM-1003|Remove the usage of laaTransactionId

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/controller/ContributionController.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/exeption/CCCExceptionHandler.java, crown-court-contribution/src/main/resources/schemas/apiMaatCheckContributionRuleRequest.json, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/ContributionControllerContributionIntegrationTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/controller/ContributionControllerTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/data/builder/TestModelDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-XXX)
=> Check Contribution Rule

crown-court-contribution/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-XXX)
=> Upgrade Sentry Version

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/CompareContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataService.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/CompareContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/ContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataServiceTest.java
[LCAM-1223](https://dsdmoj.atlassian.net/browse/LCAM-1223)
Removed the redundant logic and tidy up tests.
[LCAM-1223]: https://dsdmoj.atlassian.net/browse/LCAM-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LCAM-1223|Remove the redundant logic and tidy up tests

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/config/ServicesConfiguration.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataService.java, crown-court-contribution/src/main/resources/application.yaml, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/config/MockServicesConfiguration.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/ContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataServiceTest.java, crown-court-contribution/src/test/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1222)
Removed redundant logic and associated tests.
=> LCAM-1222|Remove redundant logic and associated tests

crown-court-contribution/build.gradle
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1259)
=> LCAM 1259 Upgraded to latest crime commons classes and rest client

crown-court-contribution/build.gradle, crown-court-contribution/src/main/resources/logback.xml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1320)
POC for Obfuscate few data for field 
=> LCAM-1320-POC-Obfuscate-sensitive-information

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/builder/ContributionDTOBuilder.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/util/CalculateContributionUtil.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/builder/ContributionDTOBuilderTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/CalculateContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/util/CalculateContributionUtilTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1477)
=> LCAM-1477-contribution testing

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1538)
CircleCI integration with slack for deployment and build notifications as detailed in this tutorial https://circleci.com/docs/slack-orb-tutorial/
=> LCAM-1538|CircleCI integration with Slack for deployment notifications

crown-court-contribution/build.gradle, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/builder/ContributionDTOBuilder.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/builder/CreateContributionRequestMapper.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/dto/CalculateContributionDTO.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/AppealContributionService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/ContributionRulesService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionService.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/builder/ContributionDTOBuilderTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/builder/CreateContributionRequestMapperTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/data/builder/TestModelDataBuilder.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/AppealContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/service/MaatCalculateContributionServiceTest.java, crown-court-contribution/src/test/java/uk/gov/justice/laa/crime/contribution/validation/AppealContributionValidatorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1576)
Using the latest schema for contribution and associated common classes. Formatted code and tidied up by removing unused variables and excessive logs.
This change has an associated PR. - https://github.com/ministryofjustice/laa-maat-orchestration/pull/199
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
=> LCAM-1576|Using the latest schema and common classes

crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/CrimeHardshipService.java, crown-court-contribution/src/main/java/uk/gov/justice/laa/crime/contribution/service/MaatCourtDataService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-XXX)
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
=> Added log statements to log the request

crown-court-contribution/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-XXX)
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
=> Upgraded crime commons classes version

helm_deploy/laa-crown-court-contribution/values-dev.yaml, helm_deploy/laa-crown-court-contribution/values-prod.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4092)
Update MAAT Data API url to point to CP in Development environment.
=> LASB-4092|Update MAAT Data API url to point to CP in Dev
